constant:
  num-like:
    HIGHEDGE_BOX: 0.8333333333333334
    LOWEDGE_BOX: 0.16666666666666666
    n_iterations: 500
    max_sample: 2
    batch_size: 1
    crop_dict:
      area_ratio: 0.5
      final_height: 0
      final_width: 100
      

  path-like:
    CONTROL_POINTS_FOLDER:
    - Main_folder
    - Modules
    - dataset
    - FIRE
    - Ground Truth
    CSV_RESULTS:
    - Main_Folder
    - Results
    - CSVResults
    DATA_COLLECTORS:
    - Main_Folder
    - Results
    - DataCollectors
    ELASTIX_IMAGE_FOLDER:
    - Main_folder
    - Results
    - ITK-Elastix
    FIRE_DATASET:
    - Main_folder
    - Modules
    - dataset
    - FIRE
    IMAGES:
    - Main_folder
    - Modules
    - dataset
    - FIRE
    - Images
    FIRE_TEST_FOLDER:
    - Main_folder
    - Modules
    - dataset
    - FIRE
    - Images
    - Test
    FIRE_REFERENCE_FOLDER:
    - Main_folder
    - Modules
    - dataset
    - FIRE
    - Images
    - Reference
    IMAGE_MASK:
    - Main_folder
    - Modules
    - dataset
    - FIRE
    - Mask
    IMG_RESULTS:
    - Main_Folder
    - Results
    - ImgRes
    Images_A:
    - Main_folder
    - Modules
    - dataset
    - FIRE
    - Images
    - Longitudinal_Studies
    Images_P:
    - Main_folder
    - Modules
    - dataset
    - FIRE
    - Images
    - Mosaicing
    Images_S:
    - Main_folder
    - Modules
    - dataset
    - FIRE
    - Images
    - Super_Resolution
    RESULTS:
    - Main_Folder
    - Results
  text-like:
    FIXED: _1
    MOVING: _2
    REFERENCE_FOLDER: Reference
    TEST_FOLDER: Test
    SAVING_FORMAT: csv
    img_normalization: same
registrations:
  DRMINE_original:
    pyramid:
      gaussian_downscale : 2
      gaussian_sigma : 1
    crop_style: ''
    early_stopping_criteria: ''
    histo_bins: 64
    lr:
      mine: 0.01
      v1: 1.0e-05
      vL: 0.001
    min_delta: .inf
    n_iterations: 500
    pyramid_levels: 6
    sampling_ratio: 0.1
    n_neurons: 100
  Personal:
    TO BE DEFINED: null
  airlab:
    early-stopping:
      patience: 30
      min_delta: 1e-7
    masked: false
    background_min: 0.0
    background_max: 0.0
    opt_cm: False
    histo_bins: 64
    lr: 0.0001
    metric_sigma: 3.0
    n_iterations: 500
    sampling_ratio: 0.1
  elastix_original:
    histo_bins: 64
    n_iterations: 5
    n_resolution: 4
    sampling_ratio: 0.5
  simpleITK_original:
    JHMI:
      convergenceMinimumValue: 1.0e-09
      convergenceWindowSize: 200
      histo_bins: 100
      lr: 0.1
      n_iterations: 5
      sampling_ratio: 0.5
    MMI:
      convergenceMinimumValue: 1.0e-09
      convergenceWindowSize: 200
      histo_bins: 100
      lr: 1.0e-05
      n_iterations: 5
      sampling_ratio: 0.5
    MSE:
      convergenceMinimumValue: 1.0e-09
      convergenceWindowSize: 200
      lr: 1.0e-06
      n_iterations: 5
      sampling_ratio: 0.5
    NCC_centred:
      convergenceMinimumValue: 1.0e-09
      convergenceWindowSize: 200
      lr: 0.1
      min_step: 1e-4
      n_iterations: 5
      gradientMagnitudeTolerance: 1e-8
      sampling_ratio: 0.5
    NCC:
      convergenceMinimumValue: 1.0e-09
      convergenceWindowSize: 200
      lr: 0.1
      n_iterations: 5
      sampling_ratio: 0.5
