# script to manage all classes regarding data management:

from typing import  Callable, TypedDict, Optional, Tuple, Dcit, List, Sequence, Required, NotRequired, Union
from pathlib import Path
import torch
from torch.utils.data import Dataset, DataLoader
from Main_Folder.Modules.configuration_setting.logger_configuration import set_logger
from torchvision import transforms
import random
from PIL import Image as PImage


standard_logs = set_logger(level='DEBUG')

class SampleDict(TypedDict):
    '''
    A TypedDict to manage data operations throught function and registrations_fn

    Compulsory Items
    ----    
    reference_sample : torch.Tensor, tensor of the image as refernce
    test_sample : torch.Tensor, tensor of the image as test
    reference_sample_path : Path, path of the reference image
    test_sample_path : Path, path of the test image
    

    Optional Items (both for test and reference)
    ----
    reference_mask : torch.Tensor, masked image (bool or int) for the refernce inmage
    test_mask:torch.Tensor, masked image (bool or int) for the test image

    reference_pyramid: list[torch.Tensor], pyramid generated by the reference image
    test_pyramid: list[torch.Tensor], pyramid generated by the test image

    sample_name : str, name of the couple of images (extracted from image's path)
    nChannel : int, number of channels in the images (RGB = 3, Grayscale or B/N = 1)
        
    '''
    reference_sample : torch.Tensor 
    reference_mask : NotRequired[torch.Tensor]
    reference_sample_path : Path
    reference_pyramid : NotRequired[list[torch.Tensor]]

    test_sample : torch.Tensor
    test_mask : NotRequired[torch.Tensor]
    test_sample_path : Path
    test_pyramid : NotRequired[list[torch.Tensor]]
    
    
    sample_name : NotRequired[str]
    nChannel : NotRequired[int]



#================================
#             DATASETs
#================================

class SimpleImRegDataSet(Dataset):
    
    '''A simple dataloader to load image pairs from a dataset in a given folder structure
    Initialization:
    ------------
    dataset_folder_path (Path): where the dataset is stored

    Methods Return
    __getitem__(idx:int) : return the tuple test_img, ref_img, path_to_test, path_to_ref
    __len__: the dimension of set of data described as len(self.test_images)
    get_nChannel(): depending the images batch it return the channel numbers, if 3 ( RGB) or 1(grayscale)'''
    def __init__(self, 
                 dataset_folder_path: Path,
                 reference_folder_name: str | Path,
                 test_folder_name: str | Path,
                 transforms=None) -> None:
        
        self.dataset_folder_path = dataset_folder_path
        self.reference_folder_name = reference_folder_name
        self.test_folder_name = test_folder_name
        self.transforms = transforms
        self.logs = standard_logs # NOTE control

        self.test_images = sorted(list(self.dataset_folder_path.glob(f'Images/{self.test_folder_name}/*/*')))
        self.reference_images = sorted(list(self.dataset_folder_path.glob(f'Images/{self.reference_folder_name}/*/*')))

    def __len__(self) -> int:
        return len(self.test_images) 

    def __getitem__(self, index: int) -> Tuple[torch.Tensor, torch.Tensor, str, str]:
        if index not in range(0, len(self.test_images)):
            self.logs.warning(f'Unable to get the {index} image, another one casually get from the dirs')
            index = random.randint(0, len(self.test_images) - 1)
        
        test_image = PImage.open(self.test_images[index]) # add .convert('RGB') to ensure the opening of a 3Channels image
        reference_image = PImage.open(self.reference_images[index]) # add .convert('RGB') to ensure the opening of a 3Channels image
        test_image_path = self.test_images[index]
        reference_image_path = self.reference_images[index]
        
        if self.transforms:
            test_image = self.transforms(test_image)
            reference_image = self.transforms(reference_image)
        
        return test_image, reference_image, str(test_image_path), str(reference_image_path)
    
    def get_nChannel(self) ->int:
        
        image_test= PImage.open(self.test_images[0]) 
        if image_test.mode == 'RGB':
            colors = 3
        elif image_test.mode == 'L':
            colors = 2 # greyscale 1
            self.logs.debug(f'nchannels == colors? {colors}')
        else:
            colors=0
        return colors



class ImageRegistrationCustom(Dataset):
    
    def __init__(self,
                dataset_folder_path: Path, # the path of FIRE dataset: Path.cwd().parent / 'Modules' / 'dataset' / 'FIRE'
                transform=None, 
                target_transform=None)->None:
        self.logs = standard_logs # NOTE to control
        self.dataset_path = dataset_folder_path
        path_to_image_types = dataset_folder_path / 'Images' 
        path_to_deformation_types = dataset_folder_path /  'Images' / 'Test' 
        self.reference_images_paths = sorted(list(dataset_folder_path.glob('Images/Reference/*/*.jpg')))
        self.test_images_paths = sorted(list(dataset_folder_path.glob('Images/Test/*/*.jpg')))
        self.transform = transform # da trasformare le singole immagini? 
        self.target_transform = target_transform
        self.image_types = [d.name for d in path_to_image_types.iterdir() if d.is_dir()]
        self.deformation_types = [d.name  for d in path_to_deformation_types.iterdir() if d.is_dir()]

    # costruisci un dict  per abbreviare long... super res e mosaicing in A, S, P ... ?
    def load_image(self, 
                   index : str | int = 'random', # valuta la possibilità di mettere il random in una funzione a parte
                   deformation: str= '') ->PImage.Image: # given an index it get an image
        ''' 
        depending the type there are different possibilities
        depending which type f deformation to visualize
        ****aggiungi la possibilità di usare una trasformazione su un'immagine di test 
        '''
        images = list(self.dataset_path.glob('*/*/*/*'))
        
        if deformation == '':
            images = list(self.dataset_path.glob('*/*/*/*'))
        else:
            if deformation not in self.deformation_types:
                self.logs.info(f'to see possibile selection use the method .deformation_types')
                raise ValueError(f"Deformation type {deformation} not found in the dataset")
            else:
                images = list(self.dataset_path.glob(f'*/*/*/{deformation}/*'))
        
        if index.lower() == 'random' or not isinstance(index, int):
            idx = random.randint(0, len(images)-1)
        elif isinstance(index, int):
            idx=index
            if index not in range(0, len(images)):
                self.logs.warning(f'Unable to get the {index} image, another one casually get from the dirs')
                idx = random.randint(0, len(images) - 1)
                images = list(self.dataset_path.glob('*/*/*/*')) 
        
        return PImage.open(images[idx])      # aggiusta in una tupla 
        

    def __len__(self,
                info : bool = True):
        '''show the distribution of sample in the dataset path
        then the number of total files in the deepest folder'''
        if info:
            for dirpath, dirnames, filenames in os.walk(self.dataset_path):
                print(f"[INFO] - There are {len(dirnames)} directories and {len(filenames)} files in '{dirpath}'.")
        return len(list(self.dataset_path.glob('*/*/*/*')))
    
    def get_coupled_imgs(self,
                    index: bool|int = False,
                    deformation_choice : str = '' 
                    ) -> Tuple[torch.Tensor, torch.Tensor, str]:
        '''get the image pairs from the list of avaiable '''
        if deformation_choice == '' or deformation_choice not in self.deformation_types:
            test_images = list(self.dataset_path.glob('*/Test/*/*'))
            reference_images = list(self.dataset_path.glob('*/Reference/*/*'))
            self.logs.warning('Not a valid choice of deformation, the entire dataset is used as a batch') 
        else: 
            test_images = list(self.dataset_path.glob(f'*/*/Test/{deformation_choice}/*'))
            reference_images = list(self.dataset_path.glob(f'Images/Reference/{deformation_choice}/*.jpg'))
        if not index or index not in range(0, len(test_images)):
            index = random.randint(0, len(test_images)-1)
            
        test_image = test_images[index]
        reference_image = reference_images[index]
        test_reference,deformation, filename = get_dirs_of(test_image)
        self.logs.info(f'the selected/chosen image is {filename}, from {deformation} folder of {test_reference}')
        if self.transform:
            reference_image = self.transform(PImage.open(reference_image))  
        if self.target_transform:
            test_image = self.target_transform(PImage.open(test_image))
        return test_image, reference_image, deformation

    def __getitem__(self, 
                    index : bool|int = False,
                    deformation_choice: str = ''):
        ''' get the images couple of reference/test as tensor tuple'''
        test_image, reference_image, _ = self.get_coupled_imgs(index=index, deformation_choice=deformation_choice)
        if self.transform:
            test_image = self.transform(test_image)
        if self.target_transform:
            reference_image = self.target_transform(reference_image)
        return test_image, reference_image 
